version: 0.2

phases:
  build:
    commands:
      - echo Entered the build phase...
      - gradle clean
      - gradle build
  post_build:
    commands:
      - echo Build completed successfully
  test:
    commands:
      - echo Test...
      - gradle test
  post_test:
    commands:
      - echo Test finished
artifacts:
  files:
    - build/libs/demo1-0.0.1-SNAPSHOT-plain.jar
  discard-paths: yes