version: 0.2

phases:
  pre_build:
    commands:
      - echo Cleaning project
      - gradle clean
  build:
    commands:
      - echo Entered the build phase...
      - gradle build
  post_build:
    commands:
      - echo Build completed successfully
      
artifacts:
  files:
    - build/libs/demo1-0.0.1-SNAPSHOT-plain.jar
  discard-paths: yes